#ifndef _SPI_ATMEGA_H_
#define _SPI_ATMEGA_H_

#include "macros.h"
#include "atmega.h"

#define SPI_MODE0 0
#define SPI_MODE1 1
#define SPI_MODE2 2
#define SPI_MODE3 3

#define SPI_MASTER 0X01U
#define SPI_SLAVE 0X00U

#define SPI_ASYNC_MODE 0X01U
#define SPI_SYNC_MODE 0X00U

#define SPI_LSB_FIRST 0x00U
#define SPI_MSB_FIRST 0X01U

#define SPI_RISING_ON_LEADING 0X00U
#define SPI_SETUP_ON_LEADING 0X01U

#define SPI_PRESCALLER_2 0X04U
#define SPI_PRESCALLER_4 0X00U
#define SPI_PRESCALLER_8 0X05U
#define SPI_PRESCALLER_16 0X01U
#define SPI_PRESCALLER_32 0X06U
#define SPI_PRESCALLER_64 0X02U
#define SPI_PRESCALLER_128 0X03

#define SPI_ENABLE_INTERRUPT() (DIO_SET_BIT(SPI->SPCR_REG, SPIE_BIT))
#define SPI_DISABLE_INTERRUPT() (DIO_CLEAR_BIT(SPI->SPCR_REG, SPIE_BIT))

#define SPI_SET_MASTER() (DIO_SET_BIT(SPI->SPCR_REG, MSTR_BIT))
#define SPI_SET_SLAVE() (DIO_CLEAR_BIT(SPI->SPCR_REG, MSTR_BIT))

#define SPI_ENABLE() (DIO_SET_BIT(SPI->SPCR_REG, SPE_BIT))
#define SPI_DISABLE() (DIO_CLEAR_BIT(SPI->SPCR_REG, SPE_BIT))

#define SPI_SET_LSB_FIRST() (DIO_SET_BIT(SPI->SPCR_REG, DORD_BIT))
#define SPI_SET_MSB_FIRST() (DIO_CLEAR_BIT(SPI->SPCR_REG, DORD_BIT))

#define SPI_SET_RISING_ON_LEADING() (DIO_CLEAR_BIT(SPI->SPCR_REG, CPOL_BIT))
#define SPI_SET_FALLING_ON_LEADING() (DIO_SET_BIT(SPI->SPCR_REG, CPOL_BIT))
#define SPI_SET_SAMPLE_ON_LEADING() (DIO_CLEAR_BIT(SPI->SPCR_REG, CPHA_BIT))
#define SPI_SET_SETUP_ON_LEADING() (DIO_SET_BIT(SPI->SPCR_REG, CPHA_BIT))

#define SPI_SET_MODE0()          \
    SPI_SET_SAMPLE_ON_LEADING(); \
    SPI_SET_RISING_ON_LEADING()

#define SPI_SET_MODE1()          \
    SPI_SET_RISING_ON_LEADING(); \
    SPI_SET_SETUP_ON_LEADING()

#define SPI_SET_MODE2()           \
    SPI_SET_FALLING_ON_LEADING(); \
    SPI_SET_SAMPLE_ON_LEADING()

#define SPI_SET_MODE3()           \
    SPI_SET_FALLING_ON_LEADING(); \
    SPI_SET_SETUP_ON_LEADING()

#endif